inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - doc/**/*
    - pkg/**/*
    - tmp/**/*
    - vendor/**/*

Layout/LineLength:
  Max: 120
  IgnoredPatterns: ['^\s*#']

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
