inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-factory_bot
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - doc/**/*
    - pkg/**/*
    - tmp/**/*
    - vendor/**/*
  SuggestExtensions:
    rubocop-rspec: false

Layout/LineLength:
  Max: 120
  AllowedPatterns: ['^\s*#']

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
