---
AllCops:
  Exclude:
    - '.git/**/*'
    - 'spec/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - pdfh.gemspec

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 15