#!/usr/bin/env ruby
# frozen_string_literal: true

require "pdfh"

exit(1) if Pdfh::Utils::DependencyValidator.missing?(*Pdfh::REQUIRED_CMDS)

begin
  Pdfh::Main.start(argv: ARGV)
rescue StandardError => e
  Pdfh.error_print e.message
end
